import http from 'node:http';import express,{type NextFunction,type Request,type Response} from 'express';import cors from 'cors';import helmet from 'helmet';import { rateLimit } from 'express-rate-limit';import { pinoHttp } from 'pino-http';import { WebSocketServer } from 'ws';import { lessons } from './lessons.js';import { explain } from './gemini.js';import { logger } from './logger.js';import type { LabManager } from './types.js';
const idPattern=/^[0-9a-f-]{36}$/;
export function createApp(manager:LabManager){const app=express();app.disable('x-powered-by');app.use(pinoHttp({logger}));app.use(helmet({contentSecurityPolicy:{directives:{defaultSrc:["'self'"],scriptSrc:["'self'"],styleSrc:["'self'","'unsafe-inline'",'https://fonts.googleapis.com'],fontSrc:["'self'",'https://fonts.gstatic.com','data:'],imgSrc:["'self'",'data:','blob:'],frameSrc:["'self'"],connectSrc:["'self'",'ws:','wss:']}}}));app.use(cors({origin:false}));app.use(express.json({limit:'24kb'}));app.use('/api',rateLimit({windowMs:60_000,limit:120,standardHeaders:'draft-7',legacyHeaders:false}));app.get('/api/health',(_req,res)=>res.json({status:'ok'}));
 app.post('/api/labs',rateLimit({windowMs:60_000,limit:5}),async(_req,res,next)=>{try{res.status(201).json(publicSession(await manager.start()))}catch(e){next(e)}});
 app.get('/api/labs/:id',(req,res)=>{const s=validSession(manager,req.params.id);res.json(publicSession(s))});
 app.delete('/api/labs/:id',async(req,res,next)=>{try{const id=req.params.id;if(typeof id!=='string'||!idPattern.test(id)||!manager.get(id))return res.status(404).json({error:'ラボが見つかりません。'});await manager.stop(id);res.json({ok:true})}catch(e){next(e)}});
 app.post('/api/labs/:id/explain',rateLimit({windowMs:60_000,limit:10}),async(req,res,next)=>{try{validSession(manager,req.params.id);const lessonId=Number(req.body.lessonId),lesson=lessons.find(l=>l.id===lessonId);if(!lesson)return res.status(400).json({error:'レッスンが不正です。'});const command=typeof req.body.command==='string'?req.body.command.slice(0,300):'',output=typeof req.body.output==='string'?stripAnsi(req.body.output).slice(-8000):'';if(!command)return res.status(400).json({error:'解説するコマンドがありません。'});res.json(await explain({lesson:lesson.title,description:lesson.description,command,output}))}catch(e){next(e)}});
 app.use('/lab/:id/target',async(req,res,next)=>{try{const s=validSession(manager,req.params.id),target=manager.target(s.sessionId);if(!target)return res.status(503).send('Target is starting.');if(target.host==='demo')return demoTarget(res);proxyTarget(req,res,target)}catch(e){next(e)}});
 app.use((error:Error,_req:Request,res:Response,_next:NextFunction)=>{logger.error({error},'request failed');res.status(error.message==='Session not found'?404:503).json({error:error.message==='Session not found'?'ラボが見つかりません。':error.message||'サーバーエラーが発生しました。'})});return app}
export function attachTerminal(server:http.Server,manager:LabManager){const wss=new WebSocketServer({noServer:true,maxPayload:16*1024});server.on('upgrade',(request,socket,head)=>{const url=new URL(request.url??'','http://localhost');if(url.pathname!=='/ws/terminal'){socket.destroy();return}const id=url.searchParams.get('sessionId')??'';if(!idPattern.test(id)||!manager.get(id)){socket.destroy();return}wss.handleUpgrade(request,socket,head,ws=>wss.emit('connection',ws,request))});wss.on('connection',async(ws,request)=>{const id=new URL(request.url??'','http://localhost').searchParams.get('sessionId')!;try{const terminal=await manager.terminal(id);let command='';terminal.onData(chunk=>{if(ws.readyState===ws.OPEN)ws.send(chunk)});terminal.onClose(()=>ws.close());ws.on('message',raw=>{const text=raw.toString();for(const c of text){if(c==='\r'){if(command.trim())logger.info({sessionId:id,command:redact(command.trim())},'command');command=''}else if(c==='\x7f')command=command.slice(0,-1);else if(c>=' '&&!c.startsWith('\x1b'))command+=c}terminal.write(raw as Buffer)});ws.on('close',()=>terminal.close());ws.on('error',()=>terminal.close())}catch{ws.close(1011,'Terminal unavailable')}});return wss}
function publicSession(s:ReturnType<LabManager['get']> extends infer _?any:never){return {sessionId:s.sessionId,createdAt:s.createdAt,expiresAt:s.expiresAt,status:s.status,demoMode:s.demoMode}}
function validSession(manager:LabManager,id:string|string[]|undefined){if(typeof id!=='string'||!idPattern.test(id))throw new Error('Session not found');const s=manager.get(id);if(!s)throw new Error('Session not found');return s}
function redact(value:string){return /(?:password|token|api[_-]?key|cookie)\s*[=:]/i.test(value)?'[REDACTED]':value.slice(0,500)}
function stripAnsi(value:string){return value.replace(/[\u001B\u009B][[\]()#;?]*(?:(?:(?:[a-zA-Z\d]*(?:;[-a-zA-Z\d\/#&.:=?%@~_]+)*)?\u0007)|(?:(?:\d{1,4}(?:[;:]\d{0,4})*)?[\dA-PR-TZcf-nq-uy=><~]))/g,'')}
function proxyTarget(req:Request,res:Response,target:{host:string;port:number}){const prefix=`/lab/${req.params.id}/target`;const path=(req.originalUrl.slice(prefix.length)||'/');const headers={...req.headers,host:`${target.host}:${target.port}`};delete headers['content-length'];const upstream=http.request({hostname:target.host,port:target.port,path,method:req.method,headers},up=>{res.status(up.statusCode??502);const html=up.headers['content-type']?.includes('text/html');for(const[key,value]of Object.entries(up.headers)){if(value!==undefined&&!['content-security-policy','x-frame-options','content-length'].includes(key))res.setHeader(key,value)}if(html){const chunks:Buffer[]=[];up.on('data',(chunk:Buffer)=>chunks.push(chunk));up.on('end',()=>{const body=Buffer.concat(chunks).toString('utf8').replace(/<base href="\/">/i,`<base href="${prefix}/">`);res.send(body)})}else up.pipe(res)});upstream.setTimeout(15_000,()=>upstream.destroy(new Error('Target timeout')));upstream.on('error',()=>{if(!res.headersSent)res.status(502).send('Target is not ready. Reload in a moment.')});req.pipe(upstream)}
function demoTarget(res:Response){res.type('html').send(`<!doctype html><html><head><style>body{margin:0;background:#fff;font-family:Arial;color:#333}.bar{height:64px;background:#546e7a;color:white;display:flex;align-items:center;padding:0 24px;font-size:21px}.main{text-align:center;padding:70px 20px}.logo{font-size:58px}.card{max-width:520px;margin:20px auto;padding:24px;border:1px solid #ddd;border-radius:8px;box-shadow:0 4px 16px #0001}</style></head><body><div class="bar">OWASP Juice Shop <small style="margin-left:auto">CyberBox Demo</small></div><div class="main"><div class="logo">🧃</div><div class="card"><h2>Target Web is ready</h2><p>Docker環境では、ここに実際のOWASP Juice Shopが表示されます。</p></div></div></body></html>`)}
