import { randomUUID } from 'node:crypto';import { PassThrough } from 'node:stream';import Docker from 'dockerode';import { config,bytes } from './config.js';import { logger } from './logger.js';import type { LabManager,LabSession,TerminalHandle } from './types.js';
class DockerTerminal implements TerminalHandle{private stream:NodeJS.ReadWriteStream;private dataHandlers:Array<(c:Buffer)=>void>=[];private closeHandlers:Array<()=>void>=[];constructor(stream:NodeJS.ReadWriteStream){this.stream=stream;stream.on('data',(c:Buffer)=>this.dataHandlers.forEach(h=>h(c)));stream.on('end',()=>this.closeHandlers.forEach(h=>h()));stream.on('error',()=>this.closeHandlers.forEach(h=>h()))}write(data:Buffer|string){this.stream.write(data)}close(){this.stream.end()}onData(h:(c:Buffer)=>void){this.dataHandlers.push(h)}onClose(h:()=>void){this.closeHandlers.push(h)}}
export class DockerLabManager implements LabManager{
 private docker:Docker;private sessions=new Map<string,LabSession>();
 constructor(){const url=new URL(config.DOCKER_HOST);this.docker=new Docker({protocol:url.protocol.replace(':','') as 'http'|'https',host:url.hostname,port:Number(url.port||2375)})}
 get(id:string){return this.sessions.get(id)}target(id:string){const s=this.sessions.get(id);return s?.targetIp?{host:s.targetIp,port:3000}:undefined}
 async start(){if(this.sessions.size>=config.MAX_LABS)throw new Error('同時に利用できるラボ数の上限に達しました。');await this.docker.ping();const id=randomUUID(),short=id.slice(0,12),now=Date.now();const session:LabSession={sessionId:id,createdAt:new Date(now).toISOString(),expiresAt:new Date(now+config.LAB_TIMEOUT_MINUTES*60_000).toISOString(),status:'starting'};this.sessions.set(id,session);
  try{await Promise.all([this.ensureImage(config.ATTACKER_IMAGE),this.ensureImage(config.TARGET_IMAGE)]);const network=await this.docker.createNetwork({Name:`cyberbox-${short}`,Internal:true,CheckDuplicate:false,Labels:{'cyberbox.session':id,'cyberbox.managed':'true'}});session.networkId=network.id;
   const target=await this.docker.createContainer({name:`cyberbox-target-${short}`,Image:config.TARGET_IMAGE,Labels:{'cyberbox.session':id,'cyberbox.role':'target'},HostConfig:{NetworkMode:network.id,Memory:bytes(config.TARGET_MEMORY_LIMIT),NanoCpus:1_000_000_000,PidsLimit:100,ReadonlyRootfs:false,CapDrop:['ALL'],SecurityOpt:['no-new-privileges:true']},NetworkingConfig:{EndpointsConfig:{[network.id]:{Aliases:['target']}}}});session.targetId=target.id;await target.start();
   const attacker=await this.docker.createContainer({name:`cyberbox-attacker-${short}`,Image:config.ATTACKER_IMAGE,Tty:true,OpenStdin:true,Cmd:['sleep','infinity'],Labels:{'cyberbox.session':id,'cyberbox.role':'attacker'},HostConfig:{NetworkMode:network.id,Memory:bytes(config.ATTACKER_MEMORY_LIMIT),NanoCpus:1_000_000_000,PidsLimit:100,ReadonlyRootfs:false,CapDrop:['ALL'],CapAdd:['NET_RAW'],SecurityOpt:['no-new-privileges:true']},NetworkingConfig:{EndpointsConfig:{[network.id]:{Aliases:['attacker']}}}});session.attackerId=attacker.id;await attacker.start();
   const backendId=process.env.HOSTNAME;if(backendId&&backendId.length>=12){try{await network.connect({Container:backendId})}catch(error){logger.warn({error},'backend network connection skipped')}}
   const info=await target.inspect();const endpoint=Object.values(info.NetworkSettings.Networks??{}).find(item=>item.NetworkID===network.id);session.targetIp=endpoint?.IPAddress;session.status='running';session.timer=setTimeout(()=>void this.stop(id),config.LAB_TIMEOUT_MINUTES*60_000);logger.info({sessionId:id},'lab started');return session;
  }catch(error){session.status='failed';await this.cleanup(session);this.sessions.delete(id);logger.error({error,sessionId:id},'lab start failed');throw new Error('ラボ環境を起動できませんでした。Dockerイメージと権限を確認してください。')}
 }
 async terminal(id:string){const s=this.sessions.get(id);if(!s?.attackerId||s.status!=='running')throw new Error('Session not found');const container=this.docker.getContainer(s.attackerId);const exec=await container.exec({Cmd:['/bin/bash','-l'],AttachStdin:true,AttachStdout:true,AttachStderr:true,Tty:true,User:'cyberbox',WorkingDir:'/home/cyberbox',Env:['TERM=xterm-256color'],Privileged:false});const stream=await exec.start({hijack:true,stdin:true,Tty:true});return new DockerTerminal(stream)}
 async stop(id:string){const s=this.sessions.get(id);if(!s)return;s.status='stopping';if(s.timer)clearTimeout(s.timer);await this.cleanup(s);s.status='stopped';this.sessions.delete(id);logger.info({sessionId:id},'lab stopped')}
 private async cleanup(s:LabSession){for(const containerId of [s.attackerId,s.targetId]){if(!containerId)continue;try{await this.docker.getContainer(containerId).remove({force:true,v:true})}catch(error){logger.warn({error,containerId},'container cleanup skipped')}}if(s.networkId){try{const backendId=process.env.HOSTNAME;if(backendId)await this.docker.getNetwork(s.networkId).disconnect({Container:backendId,Force:true})}catch{}try{await this.docker.getNetwork(s.networkId).remove()}catch(error){logger.warn({error},'network cleanup skipped')}}}
 private async ensureImage(name:string){try{await this.docker.getImage(name).inspect()}catch{logger.info({image:name},'pulling image');const stream=await this.docker.pull(name);await new Promise<void>((resolve,reject)=>this.docker.modem.followProgress(stream,(error)=>error?reject(error):resolve()))}}
 async shutdown(){await Promise.allSettled([...this.sessions.keys()].map(id=>this.stop(id)))}
}
