import { useCallback,useEffect,useMemo,useState,type ReactNode } from 'react';
import { Bot,Box,ChevronRight,CircleStop,Clock3,ExternalLink,GraduationCap,Play,ShieldCheck,Sparkles,TerminalSquare } from 'lucide-react';
import { api } from './api';import { lessons } from './lessons';import TerminalPanel from './TerminalPanel';import type { AiExplanation,LabSession } from './types';
const formatTime=(s:number)=>`${String(Math.floor(s/60)).padStart(2,'0')}:${String(s%60).padStart(2,'0')}`;
export default function App(){
 const[session,setSession]=useState<LabSession|null>(null),[selectedLesson,setSelectedLesson]=useState(lessons[0]),[secondsLeft,setSecondsLeft]=useState(3600),[busy,setBusy]=useState(false),[error,setError]=useState(''),[lastResult,setLastResult]=useState({command:'',output:''}),[explanation,setExplanation]=useState<AiExplanation|null>(null);
 useEffect(()=>{if(!session)return;const tick=()=>setSecondsLeft(Math.max(0,Math.floor((new Date(session.expiresAt).getTime()-Date.now())/1000)));tick();const timer=window.setInterval(tick,1000);return()=>clearInterval(timer)},[session]);
 const start=async()=>{setBusy(true);setError('');try{setSession(await api.startLab())}catch(e){setError(e instanceof Error?e.message:'起動に失敗しました。')}finally{setBusy(false)}};
 const stop=async()=>{if(!session)return;setBusy(true);try{await api.stopLab(session.sessionId);setSession(null);setExplanation(null)}catch(e){setError(e instanceof Error?e.message:'停止に失敗しました。')}finally{setBusy(false)}};
 const rememberOutput=useCallback((command:string,output:string)=>setLastResult({command,output}),[]);
 const explain=async()=>{if(!session||!lastResult.command)return;setBusy(true);setError('');try{setExplanation(await api.explain(session.sessionId,selectedLesson.id,lastResult.command,lastResult.output))}catch(e){setError(e instanceof Error?e.message:'AI解説を取得できませんでした。')}finally{setBusy(false)}};
 const progress=useMemo(()=>secondsLeft/36,[secondsLeft]);
 if(!session)return <main className="home"><div className="grid-noise"/><header className="home-nav"><Brand/><span className="secure-label"><ShieldCheck size={15}/> isolated learning environment</span></header><section className="hero"><div className="eyebrow"><span/> BROWSER-BASED CYBERSECURITY LABORATORY</div><h1>触れて、確かめて、<br/><em>仕組みから学ぶ。</em></h1><p>Linux、ネットワーク、Webセキュリティをブラウザだけで実践。安全に隔離された演習環境とAIの解説で、最初の一歩を支えます。</p><button className="primary large" onClick={start} disabled={busy}><Play size={18} fill="currentColor"/>{busy?'環境を準備中…':'Start Lab'}<ChevronRight size={18}/></button>{error&&<p className="error">{error}</p>}<div className="feature-row"><Feature icon={<TerminalSquare/>} title="Real Linux Terminal" text="ブラウザから本物のLinux環境へ"/><Feature icon={<Box/>} title="Isolated Containers" text="ラボごとに安全に分離"/><Feature icon={<Sparkles/>} title="Gemini Assistant" text="結果をやさしい日本語で解説"/></div></section></main>;
 return <main className="app-shell"><header className="topbar"><Brand/><div className="top-actions"><div className="timer"><Clock3 size={15}/><span>LAB TIME</span><strong>{formatTime(secondsLeft)}</strong><i style={{width:`${progress}%`}}/></div><span className="online"><b/> {session.demoMode?'DEMO':'ISOLATED'}</span><button className="stop" onClick={stop} disabled={busy}><CircleStop size={16}/> Stop Lab</button></div></header>{error&&<div className="error-bar">{error}</div>}<div className="workspace"><aside className="lessons"><div className="section-heading"><GraduationCap size={15}/> LESSONS</div>{lessons.map(lesson=><button key={lesson.id} className={selectedLesson.id===lesson.id?'lesson active':'lesson'} onClick={()=>setSelectedLesson(lesson)}><span>{String(lesson.id).padStart(2,'0')}</span><div><strong>{lesson.short}</strong><small>{lesson.title}</small></div><ChevronRight size={15}/></button>)}<div className="session-id"><span>SESSION</span><code>{session.sessionId.slice(0,12)}</code></div></aside><section className="main-grid">
 <article className="lesson-card panel"><div className="panel-title"><span><GraduationCap size={14}/> LESSON {selectedLesson.id}</span></div><div className="lesson-body"><p className="kicker">{selectedLesson.objective}</p><h2>{selectedLesson.title}</h2><p>{selectedLesson.description}</p><div className="command-chips">{selectedLesson.commands.map(c=><code key={c}>$ {c}</code>)}</div><div className="points">{selectedLesson.points.map(p=><span key={p}><i/> {p}</span>)}</div>{selectedLesson.caution&&<div className="caution">{selectedLesson.caution}</div>}</div></article>
 <article className="target panel"><div className="panel-title"><span><Box size={14}/> TARGET WEB</span><a href={`/lab/${session.sessionId}/target/`} target="_blank" rel="noreferrer"><ExternalLink size={14}/></a></div><iframe title="OWASP Juice Shop" src={`/lab/${session.sessionId}/target/`} sandbox="allow-scripts allow-forms allow-same-origin allow-popups"/></article>
 <article className="terminal panel"><div className="panel-title"><span><TerminalSquare size={14}/> TERMINAL</span><span className="shell-label">cyberbox@lab</span></div><TerminalPanel sessionId={session.sessionId} onOutput={rememberOutput}/><div className="terminal-footer"><span>{lastResult.command?`Last: ${lastResult.command}`:'コマンドを実行するとAIで解説できます'}</span><button onClick={explain} disabled={busy||!lastResult.command}><Sparkles size={14}/> Explain with Gemini</button></div></article>
 <article className="ai panel"><div className="panel-title"><span><Bot size={14}/> GEMINI AI</span><span className="ai-badge">AI</span></div><div className="ai-content">{explanation?<><h3>{explanation.summary}</h3><ul>{explanation.details.map(d=><li key={d}>{d}</li>)}</ul><div className="next"><span>NEXT STEP</span><code>{explanation.nextStep}</code></div></>:<div className="ai-empty"><Sparkles size={28}/><h3>実行結果を読み解く</h3><p>ターミナルでコマンドを実行し、<br/>「Explain with Gemini」を押してください。</p></div>}</div></article>
 </section></div></main>;
}
function Brand(){return <div className="brand"><div className="brand-mark"><span/><span/><span/></div><div><strong>CyberBox</strong><small>Browser-Based Cybersecurity Laboratory</small></div></div>}
function Feature({icon,title,text}:{icon:ReactNode;title:string;text:string}){return <div className="feature"><span>{icon}</span><div><strong>{title}</strong><small>{text}</small></div></div>}
