import { useEffect,useRef } from 'react';
import { Terminal } from '@xterm/xterm';
import { FitAddon } from '@xterm/addon-fit';
type Props={sessionId:string;onOutput:(command:string,output:string)=>void};
export default function TerminalPanel({sessionId,onOutput}:Props){
 const host=useRef<HTMLDivElement>(null),outputBuffer=useRef(''),commandBuffer=useRef('');
 useEffect(()=>{if(!host.current)return;const terminal=new Terminal({cursorBlink:true,fontSize:13,fontFamily:'"JetBrains Mono", "Cascadia Code", monospace',theme:{background:'#080d12',foreground:'#d7e2ea',cursor:'#43f5c5',selectionBackground:'#21495a'},scrollback:3000});const fit=new FitAddon();terminal.loadAddon(fit);terminal.open(host.current);fit.fit();const protocol=location.protocol==='https:'?'wss:':'ws:';const socket=new WebSocket(`${protocol}//${location.host}/ws/terminal?sessionId=${encodeURIComponent(sessionId)}`);socket.binaryType='arraybuffer';socket.onopen=()=>terminal.focus();socket.onmessage=(event)=>{const text=typeof event.data==='string'?event.data:new TextDecoder().decode(event.data);terminal.write(text);outputBuffer.current+=text;if(outputBuffer.current.length>20000)outputBuffer.current=outputBuffer.current.slice(-20000)};socket.onerror=()=>terminal.writeln('\r\n\x1b[31mTerminal connection failed.\x1b[0m');const input=terminal.onData((data)=>{if(data==='\r'){const command=commandBuffer.current.trim();if(command)setTimeout(()=>onOutput(command,outputBuffer.current),700);commandBuffer.current='';outputBuffer.current=''}else if(data==='\x7f')commandBuffer.current=commandBuffer.current.slice(0,-1);else if(!data.startsWith('\x1b')&&data>=' ')commandBuffer.current+=data;if(socket.readyState===WebSocket.OPEN)socket.send(data)});const observer=new ResizeObserver(()=>fit.fit());observer.observe(host.current);return()=>{observer.disconnect();input.dispose();socket.close();terminal.dispose()}},[sessionId,onOutput]);
 return <div className="terminal-host" ref={host} aria-label="CyberBox terminal"/>;
}
